# Generated by Django 4.1.7 on 2023-05-09 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simpleuser",
            name="user_auth",
        ),
    ]
