# Generated by Django 4.1.7 on 2023-04-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="friends",
            field=models.ManyToManyField(null=True, related_name="f", to="app.simpleuser"),
        ),
        migrations.AlterField(
            model_name="simpleuser",
            name="transactions_history",
            field=models.ManyToManyField(null=True, to="app.transactionlog"),
        ),
    ]
