# Generated by Django 4.1.7 on 2023-05-02 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="login_access",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("Jti", models.CharField(max_length=10000)),
                ("token_type", models.CharField(max_length=20)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.simpleuser")),
            ],
        ),
    ]
