# Generated by Django 4.1.7 on 2023-05-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="login_access",
            field=models.BooleanField(default=True),
        ),
    ]
