# Generated by Django 4.1.7 on 2023-05-02 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, default=0, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_recipient",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recipients", to="app.simpleuser"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_sender",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="senders", to="app.simpleuser"
            ),
        ),
    ]
