# Generated by Django 4.1.7 on 2023-04-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpleuser",
            name="full_username",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
