# Generated by Django 4.1.7 on 2023-03-08 23:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="amount",
            new_name="currency_amount",
        ),
    ]
