# Generated by Django 4.1.6 on 2023-02-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_simpleuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
