# Generated by Django 4.1.7 on 2023-04-20 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_simpleuser_full_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simpleuser",
            name="friends",
        ),
        migrations.CreateModel(
            name="FriendBackLoop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="b", to="app.simpleuser"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="a", to="app.simpleuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("followers", models.ManyToManyField(related_name="followees", to="app.customuser")),
            ],
        ),
        migrations.AddField(
            model_name="simpleuser",
            name="friends",
            field=models.ManyToManyField(related_name="f", to="app.simpleuser"),
        ),
    ]
