# Generated by Django 4.1.7 on 2023-05-03 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_simpleuser_login_access_refreshtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refreshtoken",
            name="token_type",
        ),
    ]
