# Generated by Django 4.1.7 on 2023-04-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_simpleuser_hash_of_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="hash_of_password",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
