# Generated by Django 4.1.7 on 2023-03-08 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_simpleuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingAccount',
            fields=[
                ('account_number', models.IntegerField(primary_key=True, serialize=False)),
                ('currency_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.IntegerField(primary_key=True, serialize=False)),
                ('MM', models.IntegerField(max_length=255)),
                ('YY', models.IntegerField(max_length=255)),
                ('system', models.CharField(max_length=20)),
                ('banking_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bankingaccount')),
                ('card_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
