# Generated by Django 4.1.7 on 2023-04-27 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_simpleuser_hash_of_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                ("jti", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_revoked", models.BooleanField(default=False)),
                ("device_id", models.UUIDField(unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="refresh_token", to="app.simpleuser"
                    ),
                ),
            ],
        ),
    ]
