# Generated by Django 4.1.7 on 2023-03-11 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_simpleuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="MM",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="YY",
            field=models.IntegerField(),
        ),
    ]
