# Generated by Django 4.1.7 on 2023-05-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_refreshtoken_token_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refreshtoken",
            name="id",
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="Jti",
            field=models.CharField(max_length=10000, primary_key=True, serialize=False),
        ),
    ]
