# Generated by Django 4.1.7 on 2023-03-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_card_mm_alter_card_yy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='currency_amount',
        ),
    ]
