# Generated by Django 4.1.7 on 2023-04-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_refreshtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="jti",
            field=models.CharField(max_length=2500, primary_key=True, serialize=False),
        ),
    ]
