# Generated by Django 4.1.7 on 2023-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_refreshtoken_id_alter_refreshtoken_jti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="user_id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
