# Generated by Django 4.1.7 on 2023-03-08 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bankingaccount_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankingaccount',
            name='account_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simpleuser'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simpleuser'),
        ),
    ]
