# Generated by Django 4.1.7 on 2023-03-13 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_card_currency_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="card_owner",
        ),
    ]
