# Generated by Django 4.1.7 on 2023-05-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_simpleuser_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="user_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
