# Generated by Django 4.1.7 on 2023-03-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bankingaccount_account_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_owner',
        ),
    ]
