# Generated by Django 4.1.7 on 2023-04-27 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_refreshtoken_device_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                ("jti", models.CharField(max_length=2500, primary_key=True, serialize=False)),
                ("token_type", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="refresh_token", to="app.simpleuser"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RefreshToken",
        ),
    ]
