# Generated by Django 4.1.7 on 2023-04-27 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_authtoken_delete_refreshtoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authtoken",
            old_name="jti",
            new_name="Jti",
        ),
    ]
