# Generated by Django 4.1.7 on 2023-03-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_card_banking_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="banking_account",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="app.bankingaccount"),
        ),
    ]
