# Generated by Django 4.1.7 on 2023-03-27 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_card_banking_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simpleuser",
            old_name="name",
            new_name="user_name",
        ),
    ]
