# Generated by Django 4.1.7 on 2023-04-06 04:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_squashed_0009_rename_name_simpleuser_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpleuser",
            name="money_users",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=10
            ),
        ),
    ]
