# Generated by Django 4.1.7 on 2023-04-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_simpleuser_login_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="hash_of_password",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
