# Generated by Django 4.1.7 on 2023-04-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_squashed_0009_rename_name_simpleuser_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpleuser",
            name="relationships",
            field=models.JSONField(default='{"money_friends": []}'),
        ),
    ]
