# Generated by Django 4.1.7 on 2023-04-06 00:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_simpleuser_relationships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="relationships",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50), size=10
            ),
        ),
    ]
