# Generated by Django 4.1.7 on 2023-04-06 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_simpleuser_money_friends"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simpleuser",
            old_name="money_friends",
            new_name="money_users",
        ),
    ]
