# Generated by Django 4.1.7 on 2023-04-06 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_simpleuser_money_users_simpleuser_relationships"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simpleuser",
            name="money_users",
        ),
        migrations.RemoveField(
            model_name="simpleuser",
            name="relationships",
        ),
    ]
